### ISSUE TITLE
Unable to create VSM using the curl command example mentioned in the readme. 

### ISSUE THREAD

**Issue by kmova** [openebs/mayaserver#9]
Using the steps currently mentioned, I am getting the following errors:

```
ubuntu@kubemaster-01:~/demo/k8s/spec$ curl -k -H "Content-Type: application/yaml" -XPOST -d"$(./sample_openebs_pvc.yaml)" http://172.28.128.5:5656/latest/volumes/
-bash: ./sample_openebs_pvc.yaml: Permission denied
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

I verified that the connectivity is there and the mayaserver is running:

```
ubuntu@kubemaster-01:~/demo/k8s/spec$ curl http://172.28.128.5:5656/latest/meta-data/instance-id
"any-compute"
```

The yaml file is in the right location with 755 permission. The content is as follows:

```
ubuntu@kubemaster-01:~/demo/k8s/spec$ cat sample_openebs_pvc.yaml 
# Similar to K8s' PersistentVolumeClaim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vsm1-vol1
  labels:
    region: global
    datacenter: dc1
    jivafeversion: openebs/jiva:latest
    jivafenetwork: host
    jivafeip: 172.28.128.101
    jivabeip: 172.28.128.102
    jivafesubnet: 24
    jivafeinterface: enp0s8
  annotations:
    volume.beta.openebs.io/orchestrator-class: nomad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

**Comment by yudaykiran** [comment]
Testcases:
----------
Case_1 :
`curl http://172.28.128.3:5656/latest/volume/provision/mycoolvol`

Case_2 :
`curl -k -H "Content-Type: application/yaml" -XPOST -d"$(./sample_openebs_pvc.yaml)" http://172.28.128.5:5656/latest/volumes/`

Observation:
-------------
1. The old api works in 0.0.4, but fails in version 0.0.5.
2. Outputs "Invalid Method" on execution.
3. The new api throws "Permission Denied" error.

Version Tested:
----------------
Maya: ver 0.0.9
Mayaserver: ver 0.0.4 & 0.0.5

**Comment by kmova** [comment]
The user will only need to specify the name of the volume and the size to begin with. 

The mayaserver should be able to create a volume using the following minimal spec:

```
ubuntu@kubemaster-01:~/demo/k8s/spec$ cat sample_openebs_pvc.yaml 
# Similar to K8s' PersistentVolumeClaim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vsm1-vol1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```
