### ISSUE TITLE
Enable node-affinity feature on jiva replicas

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/mayaserver#91]
There will be cases where a K8s deployment will need replicas to be placed based on certain characteristics of node e.g. ssd attached node, etc.

Maya api service should be able to accept such requirements with ease & enable these provisions.

**Comment by AmitKumarDas** [comment]
```
# to get the names of k8s cluster nodes
kubectl get nodes
# syntax to label the node
kubectl label nodes <node-name> <label-key>=<label-value>
# get the nodes with their labels
kubectl get nodes --show-labels
```

- It will be good to add label-key=label-value to OpenEBS minion nodes as follows:
  - openebs.io/replica-1=1
  - openebs.io/replica-2=2
  - openebs.io/replica-3=3
  - & so on
- These replicas may reside in a cluster within a zone or outside it. The Admin or the Operator or storage bot, etc should take a call & label the nodes accordingly.
- In absence of above, maya api server shall try to simply place the `OpenEBS containers` & later (i.e. immediate update after placement) assign node selector i.e. node affinity tags to these pods.
  - These nodeAffinity policy will make use of `kubernetes.io/hostname` as the key & the node's hostname as the value

**Comment by AmitKumarDas** [comment]
#### Details

- Added --feature-gates=TaintBasedEvictions=true in kube-controller-manager launch config

```bash
ubuntu@kubemaster-01:/vagrant$ sudo cat /etc/kubernetes/manifests/kube-controller-manager.yaml 
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --use-service-account-credentials=true
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --leader-elect=true
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --address=127.0.0.1
    - --feature-gates=TaintBasedEvictions=true
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.7.0
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
status: {}
```
